In [5]:
#first code snippet
marks=[78,63,62]
avg=sum(marks)/len(marks)
print(avg)

67.66666666666667

In [6]:
#second code snippet
def calculate_average(marks):
    return sum(marks)
marks=[78,63,62]
print(calculate_average(marks))

203

In [9]:
#reusability
#parameters
#write a single function(reusable) to filter stuednts pass or fail based on the condition:that the student gets 27
def passorfail(marks):
    if marks>=27:
        return "Pass"
    return "Fail"

print(passorfail(12))
print(passorfail(76))

Fail
Pass

Python list=>good for general purpose,can hold any data types or mixed data types.
good for normal programming.
operations need loops.

numpy array=>numerical data focused,usually holds one mmain numeric type...
good for mathematical operations.
operations can apply to the whole array.

In [ ]:
#will give error
marks=[78,63,62]
print(marks+10)

TypeError: can only concatenate list (not "int") to list

In [11]:
import numpy as np
marks_array=np.array([78,63,62])
print(marks_array+10)

[88 73 72]

In [ ]:
#shape:the structure of the array
#index:the position of an element
#axis:the direction of the calculation across rows or columns or XYZ axis

In [12]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)
print(arr.shape)

matrix=np.array([
    [10,20,30],
    [40,50,60]
])
print(matrix)
print(matrix.shape)

[10 20 30 40]
(4,)
[[10 20 30]
 [40 50 60]]
(2, 3)

In [ ]:
#indexing and slicing
grid=np.array([
    [11,12,13,14,15],
    [21,22,23,24,25],
    [31,32,33,34,35],
    [41,42,43,44,45],
    [51,52,53,54,55]
])
print(grid[0,0])
print(grid[0])
print(grid[:,0])
print(grid[0:3,0:3])
print(grid[1:4,1:4])

11
[11 12 13 14 15]
[11 21 31 41 51]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[22 23 24]
 [32 33 34]
 [42 43 44]]

In [24]:
#filtering
marks=np.array([78,91,55,72,40,88])
print(marks>70)
high_scores=marks[marks>70]
print(high_scores)

[ True  True False  True False  True]
[78 91 72 88]

In [27]:
marks=np.array([78,91,55,72,40,88])
print(marks.mean())
print(marks.min())
print(marks.max())
print(marks.sum())

70.66666666666667
40
91
424

In [28]:
#find the class average,highest score,lowest score and count the students above 75

li=[78, 91, 55, 72, 40, 88,98,81,11,23,78,88,91,96]
count=0
for i in li:
    if i>75:
        count=count+1
print(count)
print(sum(li)/len(li))
print(max(li))
print(min(li))

9
70.71428571428571
98
11

In [ ]:
import pandas as pd

In [38]:
df=pd.read_csv("session4_dummy.csv")

In [56]:
print(df.head())
print(df.columns)
print(df.shape)
print(df.describe())

   student_id   name  age     city  math  science  english  \
0         101  Aarav   16   Mumbai    78       84       69
1         102   Diya   16    Delhi    91       88       94
2         103  Kabir   17  Mathura    55       61       58
3         104  Meera   16    Noida    72       79       81
4         105  Rohan   17   Mumbai    40       52       47

   attendance_percent  study_hours_per_week  assignments_submitted  \
0                  92                     8                      9
1                  96                    11                     10
2                  75                     5                      6
3                  89                     7                      8
4                  68                     3                      5

   final_project_score    average
0                   82  77.000000
1                   93  91.000000
2                   60  58.000000
3                   78  77.333333
4                   45  46.333333
Index(['student_id', 'name', 'age', 'city', 'math', 'science', 'english',
       'attendance_percent', 'study_hours_per_week', 'assignments_submitted',
       'final_project_score', 'average'],
      dtype='str')
(20, 12)
       student_id        age       math    science    english  \
count    20.00000  20.000000  20.000000  20.000000  20.000000
mean    110.50000  16.450000  69.500000  72.350000  72.200000
std       5.91608   0.510418  18.446223  15.383775  17.157475
min     101.00000  16.000000  35.000000  45.000000  42.000000
25%     105.75000  16.000000  57.250000  60.000000  59.500000
50%     110.50000  16.000000  73.000000  74.500000  75.500000
75%     115.25000  17.000000  84.250000  85.250000  86.000000
max     120.00000  17.000000  95.000000  93.000000  96.000000

       attendance_percent  study_hours_per_week  assignments_submitted  \
count           20.000000             20.000000              20.000000
mean            83.850000              7.250000               7.750000
std             11.089469              3.092861               1.915999
min             62.000000              2.000000               4.000000
25%             76.500000              5.000000               6.000000
50%             87.500000              7.500000               8.000000
75%             92.500000              9.250000               9.250000
max             98.000000             13.000000              10.000000

       final_project_score    average
count            20.000000  20.000000
mean             73.650000  71.350000
std              17.439444  16.752926
min              39.000000  40.666667
25%              62.250000  57.833333
50%              78.500000  76.833333
75%              87.250000  84.166667
max              96.000000  92.666667

In [57]:
math_scores=df["math"].to_numpy()
print(math_scores)
print(type(math_scores))
print(math_scores.mean())

[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
<class 'numpy.ndarray'>
69.5

In [ ]:
#calculate the average score across the other two subjects
#filtering
#top students average more than or equal to 85
df["average"]=df[["math","science","english"]].mean(axis=1)
print(df[["name","math","science","english","average"]])

top_students=df[df["average"]>=85]
print(top_students[["name","average"]])

      name  math  science  english    average
0    Aarav    78       84       69  77.000000
1     Diya    91       88       94  91.000000
2    Kabir    55       61       58  58.000000
3    Meera    72       79       81  77.333333
4    Rohan    40       52       47  46.333333
5     Sara    88       93       90  90.333333
6   Ishaan    64       70       66  66.666667
7   Ananya    95       92       89  92.000000
8   Vivaan    48       57       51  52.000000
9     Tara    83       76       85  81.333333
10   Arjun    67       63       72  67.333333
11   Nisha    74       81       79  78.000000
12     Dev    35       45       42  40.666667
13   Priya    89       86       91  88.666667
14   Kunal    58       54       60  57.333333
15    Riya    92       90       96  92.666667
16      Om    61       69       65  65.000000
17   Aditi    80       85       83  82.666667
18    Yash    43       49       46  46.000000
19   Sneha    77       73       80  76.666667
      name    average
1     Diya  91.000000
5     Sara  90.333333
7   Ananya  92.000000
13   Priya  88.666667
15    Riya  92.666667

In [ ]:
#Making filters
#low attendance,if attendance percentage is less than 75 then
low_attendance=df[df["attendance_percent"]<75]
print(low_attendance[["name","attendance_percent"]])

      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66

In [61]:
#if students are from Mathura....display their name,city and average
mathura_students=df[df["city"]=="Mathura"]
print(mathura_students[["name","city","average"]])

      name     city    average
2    Kabir  Mathura  58.000000
6   Ishaan  Mathura  66.666667
10   Arjun  Mathura  67.333333
14   Kunal  Mathura  57.333333
18    Yash  Mathura  46.000000

STUDENT PERFORMANCE ANALYSER

1.Read session4_dummy_students.csv.

2.Create an average column using math, science, and english.

3.Create a result column: Pass if average >= 40, otherwise Fail.

4.Print class average.

5.Print highest average and lowest average.

6.Print top student or students.

7.Print students with attendance below 75.

8.Print students who submitted fewer than 6 assignments.

9.Save final output as session4_student_report.csv.

In [62]:
#1.
dff=pd.read_csv("session4_dummy.csv")

In [64]:
#2.
dff['average'] = df[['math', 'science', 'english']].mean(axis=1)
dff

,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score,average
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82,77.000000
1,102,Diya,16,Delhi,91,88,94,96,11,10,93,91.000000
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60,58.000000
3,104,Meera,16,Noida,72,79,81,89,7,8,78,77.333333
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45,46.333333
5,106,Sara,16,Delhi,88,93,90,97,10,10,95,90.333333
6,107,Ishaan,17,Mathura,64,70,66,82,6,7,69,66.666667
7,108,Ananya,16,Noida,95,92,89,94,12,10,91,92.000000
8,109,Vivaan,17,Mumbai,48,57,51,71,4,6,55,52.000000
9,110,Tara,16,Delhi,83,76,85,90,9,9,86,81.333333
10,111,Arjun,17,Mathura,67,63,72,80,6,8,70,67.333333
11,112,Nisha,16,Noida,74,81,79,88,8,8,80,78.000000
12,113,Dev,17,Mumbai,35,45,42,62,2,4,39,40.666667
13,114,Priya,16,Delhi,89,86,91,95,10,10,92,88.666667
14,115,Kunal,17,Mathura,58,54,60,77,5,6,63,57.333333
15,116,Riya,16,Noida,92,90,96,98,13,10,96,92.666667
16,117,Om,17,Mumbai,61,69,65,79,6,7,68,65.000000
17,118,Aditi,16,Delhi,80,85,83,91,9,9,84,82.666667
18,119,Yash,17,Mathura,43,49,46,66,3,5,48,46.000000
19,120,Sneha,16,Noida,77,73,80,87,8,8,79,76.666667

In [ ]:
#3.
dff['result'] = dff['average'].apply(lambda x: 'Pass' if x >= 40 else 'Fail')

,student_id,name,age,city,math,science,english,attendance_percent,study_hours_per_week,assignments_submitted,final_project_score,average,result
0,101,Aarav,16,Mumbai,78,84,69,92,8,9,82,77.000000,Pass
1,102,Diya,16,Delhi,91,88,94,96,11,10,93,91.000000,Pass
2,103,Kabir,17,Mathura,55,61,58,75,5,6,60,58.000000,Pass
3,104,Meera,16,Noida,72,79,81,89,7,8,78,77.333333,Pass
4,105,Rohan,17,Mumbai,40,52,47,68,3,5,45,46.333333,Pass
5,106,Sara,16,Delhi,88,93,90,97,10,10,95,90.333333,Pass
6,107,Ishaan,17,Mathura,64,70,66,82,6,7,69,66.666667,Pass
7,108,Ananya,16,Noida,95,92,89,94,12,10,91,92.000000,Pass
8,109,Vivaan,17,Mumbai,48,57,51,71,4,6,55,52.000000,Pass
9,110,Tara,16,Delhi,83,76,85,90,9,9,86,81.333333,Pass
10,111,Arjun,17,Mathura,67,63,72,80,6,8,70,67.333333,Pass
11,112,Nisha,16,Noida,74,81,79,88,8,8,80,78.000000,Pass
12,113,Dev,17,Mumbai,35,45,42,62,2,4,39,40.666667,Pass
13,114,Priya,16,Delhi,89,86,91,95,10,10,92,88.666667,Pass
14,115,Kunal,17,Mathura,58,54,60,77,5,6,63,57.333333,Pass
15,116,Riya,16,Noida,92,90,96,98,13,10,96,92.666667,Pass
16,117,Om,17,Mumbai,61,69,65,79,6,7,68,65.000000,Pass
17,118,Aditi,16,Delhi,80,85,83,91,9,9,84,82.666667,Pass
18,119,Yash,17,Mathura,43,49,46,66,3,5,48,46.000000,Pass
19,120,Sneha,16,Noida,77,73,80,87,8,8,79,76.666667,Pass

In [67]:
#4.
class_avg = dff['average'].mean()
print("Class Average:", class_avg)

Class Average: 71.35000000000001

In [68]:
#5.
high = dff['average'].max()
low = dff['average'].min()
print("Highest Average:", high)
print("Lowest Average:", low)

Highest Average: 92.66666666666667
Lowest Average: 40.666666666666664

In [70]:
#6.
top= dff[dff['average'] == high]
print(top['name'])

15    Riya
Name: name, dtype: str

In [71]:
#7.
low_attendance = dff[dff['attendance_percent'] < 75]
print(low_attendance['name'])

4      Rohan
8     Vivaan
12       Dev
18      Yash
Name: name, dtype: str

In [76]:
#8.
names=dff[dff['attendance_percent'] < 75]['name']
print(names)

4      Rohan
8     Vivaan
12       Dev
18      Yash
Name: name, dtype: str

In [77]:
#9.
dff.to_csv('session4_newReport.csv', index=False)